swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /projects:
    get:
      operationId: projects.read_all
      tags:
        - Projects
      summary: Read the entire list of projects
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: array
            items:
              properties:
                projectid:
                  type: integer
                name:
                  type: string
                isarchived:
                  type: boolean
                createdat:
                  type: string
                lastupdated:
                  type: string