openapi: 3.0.0
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger, Innovatieplatform

servers:
  - url: http://127.0.0.1:5000/api


  # Paths supported by the server application
paths:
  /projects:
    get:
      operationId: routes.project.read_all
      tags:
        - Project
      summary: Read the entire list of projects
      responses:
        200:
          description: Successfully read projects list operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
  /projects/{projectid}:
    get:
      operationId: routes.project.read_one
      tags:
        - Project
      summary: Read the entire list of projects
      parameters:
        - in: path
          name: projectid
          required: true
          schema:
            type: string
      responses:
        200:
          description: Successfully read project operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        404:
          description: Project with id not found
    put:
      operationId: routes.project.update
      tags:
        - Project
      summary: Update a value of project
      parameters:
        - in: path
          name: projectid
          required: true
          schema:
            type: string
        - in: query
          name: isarchived
          required: true
          schema:
            type: boolean
      responses:
        200:
          description: Project updated
        404:
          description: Project with id not found
    delete:
      operationId: routes.project.delete
      tags:
        - Project
      summary: Deletes the specified project
      parameters:
        - in: path
          name: projectid
          required: true
          schema:
            type: string
      responses:
        200:
          description: Project deleted
        404:
          description: Project with id not found


  /projects/{projectid}/announcements:
    get:
      operationId: routes.announcements.read_all
      tags:
        - Announcements
      summary: Get all announcements from project
      parameters:
        - in: path
          name: projectid
          required: true
          schema:
            type: string
      responses:
        200:
          description: Succesfully retrieved announcements from project
        404:
          description: Specified project not found
    post:
      operationId: routes.announcements.post
      tags:
        - Announcements
      summary: Post announcements in project
      parameters:
        - in: path
          name: projectid
          required: true
          schema:
            type: string
      responses:
        200:
          description: Succesfully posted announcement to project
        404:
          description: Specified project not found


  /users/{userid}/projects:
    get:
      operationId: routes.user.read_user_projects
      tags:
        - Users
      summary: Get projects of specified user
      parameters:
        - in: path
          name: userid
          required: true
          schema:
            type: string
      responses:
        200:
          description: Succesfully read user projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        404:
          description: Specified user not found

components:
  schemas:
    Project:
      type: object
      properties:
        projectid:
          type: integer
        name:
          type: string
        isarchived:
          type: boolean
        createdat:
          type: string
        lastupdated:
          type: string

