version: '2.2'

services:
  api:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: DockerFile-api
      args:
        - NODE_ENV=local
    ports:
      - "127.0.0.1:5000:5000"
    networks:
      innovatie_net:
        ipv4_address: 172.28.1.1
  web-app:
    build:
      context: .
      dockerfile: DockerFile-webapp
      args:
        - NODE_ENV=local
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      innovatie_net:
        ipv4_address: 172.28.1.2
  mariadb:
    build:
      context: .
      dockerfile: DockerFile-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: innovatieplatform
      MYSQL_USER: root@innovatieplatform
      MYSQL_PASSWORD: admin
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      innovatie_net:
        ipv4_address: 172.28.1.3
  nginx:
    build:
      context: .
      dockerfile: DockerFile-proxy
    ports:
      - "127.0.0.1:80:80"
    networks:
      innovatie_net:
        ipv4_address: 172.28.1.4
networks:
  innovatie_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
