version: '2.2'

services:
  api:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: DockerFile-api
      args:
        - NODE_ENV=local
    ports:
      - "5000:5000"
  web-app:
    build:
      context: .
      dockerfile: DockerFile-webapp
      args:
        - NODE_ENV=local
    ports:
      - "8080:8080"
  mariadb:
    build:
      context: .
      dockerfile: DockerFile-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: innovatieplatform
      MYSQL_USER: root@innovatieplatform
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
