version: '2.2'

services:
  api:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: DockerFile-api
      args:
        - NODE_ENV=local
    ports:
      - "5000:5000"
  web-app:
    build:
      context: .
      dockerfile: DockerFile-webapp
      args:
        - NODE_ENV=local
    ports:
      - "8080:8080"
  database:
    volumes:
      - ./backend/database/innovatiehuis1.sql:/docker-entrypoint-initdb.d
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: innovatieplatform
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
