FROM node:lts-alpine



# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY /intranet-project/ /intranet-project/

# make the 'app' folder the current working directory
WORKDIR /intranet-project


# install simple http server for serving static content
RUN npm install -g http-server

# install project dependencies
RUN npm install


# build app for production with minification
RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]