openapi: 3.0.3
info:
  description: This is the openapi file that goes with our server code
  version: "1.0.0"
  title: Swagger, Innovatieplatform

servers:
  - url: http://127.0.0.1:5000/api



  # Paths supported by the server application
paths:
# ============================================PROJECTS==================================================
  /projects:
    get:
      operationId: src.endpoints.projects.read_all
      tags:
        - Project
      summary: Read the entire list of projects
      responses:
        200:
          description: Successfully read projects list operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
  /projects/{id}:
    get:
      operationId: src.endpoints.projects.read_one
      tags:
        - Project
      summary: Read one project
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully read project operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
    put:
      operationId: src.endpoints.projects.update
      tags:
        - Project
      summary: Update a value of project
      parameters:
        - $ref: '#/components/parameters/id'
        - in: query
          name: is_archived
          required: true
          schema:
            type: boolean
      responses:
        200:
          description: Project updated
    delete:
      operationId: src.endpoints.projects.delete
      tags:
        - Project
      summary: Deletes the specified project
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Project deleted
  /projects/{id}/parents:
    get:
      operationId: src.endpoints.projects.read_parents
      tags:
        - Project
      summary: Read all projects marked as parent of a specific project
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully read project operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
  /projects/{id}/children:
    get:
      operationId: src.endpoints.projects.read_children
      tags:
        - Project
      summary: Read all projects marked as child of a specific project
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully read project operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'

#  /projects/upload:
#    post:
#      operationId: src.endpoints.files.uploadFiles
#      tags:
#        - Files
#      summary: Uploads file(s) to filestorage
#      requestBody:
#        required: true
#        content:
#          multipart/form-data:
#            schema:
#              type: object
#              properties:
#                files:
#                  type: array
#      responses:
#        200:
#          description: Successfully uploaded a file

  /projects/{id}/files:
    get:
      operationId: src.endpoints.files.getFilesInPath
      tags:
        - Files
      summary: Returns file(s) in directory
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/path'
      responses:
        200:
          description: Successfully retrieved files at given path
    post:
      operationId: src.endpoints.files.uploadFiles
      tags:
        - Files
      summary: Upload file(s) in directory
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/path'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
      responses:
        200:
          description: Succesfully uploaded file
    put:
      operationId: src.endpoints.files.moveFile
      tags:
        - Files
      summary: Move file to another directory
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
      responses:
        200:
          description: Successfully moved file
  /projects/{id}/file:
    get:
      operationId: src.endpoints.files.downloadFile
      tags:
        - Files
      summary: Download file
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/path'
      responses:
        200:
          description: Downloaded file
    delete:
      operationId: src.endpoints.files.deleteFile
      tags:
        - Files
      summary: Delete file(s) in directory
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/path'
      responses:
        200:
          description: Succesfully deleted file
    put:
      operationId: src.endpoints.files.renameFile
      tags:
        - Files
      summary: Update file
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/path'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string

      responses:
        200:
          description: Successfully updated file

  /projects/{id}/folders:
    get:
      operationId: src.endpoints.folders.getFoldersInPath
      tags:
        - Folders
      summary: Returns folder(s) in directory
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/path'
      responses:
        200:
          description: Successfully retrieved folders at given path
    put:
      operationId: src.endpoints.folders.checkFolderPutRequest
      tags:
        - Folders
      summary: Move folder to another directory
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
                rename:
                  type: string
      responses:
        200:
          description: Successfully moved folder
        400:
          description: Failed to move folder
    delete:
      operationId: src.endpoints.folders.deleteDir
      tags:
        - Folders
      summary: Delete folder and file(s) in directory
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/path'
      responses:
        200:
          description: Succesfully delete folder
    post:
      operationId: src.endpoints.folders.createDirFromRequest
      tags:
        - Folders
      summary: Place new folder directory
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/path'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        200:
          description: Succesfully add new folder

  /projects/{id}/announcements:
    get:
      operationId: src.endpoints.projects.read_announcements
      tags:
        - Announcements
      summary: Get all announcements from project
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully retrieved announcements from project
        404:
          description: Specified project not found
    post:
      operationId: src.endpoints.projects.add_announcement
      tags:
        - Announcements
      summary: Post announcements in project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Announcement'
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully posted announcement to project

# ================================ANNOUNCEMENTS===================================
  /announcements:
    get:
      operationId: src.endpoints.announcements.read_global
      tags:
        - Global Announcements
      summary: Reads all global announcements (those not tied to any project)
      responses:
        200:
          description: Successfully retreieved global announcements
    post:
      operationId: src.endpoints.announcements.create_global
      tags:
        - Global Announcements
      summary: Create a new global announcement (not tied to any project)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Announcement'
      responses:
        200:
          description: Successfully posted announcement to project
  /announcements/{id}:
    get:
      operationId: src.endpoints.announcements.read_one
      tags:
        - Announcements
      summary: Reads a specific announcement
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully retrieved single announcement
    put:
      operationId: src.endpoints.announcements.update
      tags:
        - Announcements
      summary: Update title and/or content of a specific announcement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Announcement'
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully posted announcement to project
    delete:
      operationId: src.endpoints.announcements.delete
      tags:
        - Announcements
      summary: Deletes specific announcement
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully removed announcement
  /announcements/{id}/replies:
    get:
      operationId: src.endpoints.announcements.read_replies
      tags:
        - Replies
      summary: Get all replies to an announcement
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully retrieved replies to announcements
    post:
      operationId: src.endpoints.announcements.add_reply
      tags:
        - Replies
      summary: Post reply to an announcement
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                title:
                  type: string
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully posted reply to announcement


# =========================================REPLIES===============================================
  /replies/{id}:
    put:
      operationId: src.endpoints.replies.update
      tags:
        - Replies
      summary: Edit reply message
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully edited reply content
    delete:
      operationId: src.endpoints.replies.delete
      tags:
        - Replies
      summary: Delete reply
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully deleted reply


# ==============================================USERS==================================================
  /users:
    get:
      operationId: src.endpoints.users.read_all
      tags:
        - Users
      summary: Gets all users
      responses:
        200:
          description: Successfully read all users
    post:
      operationId: src.endpoints.users.create
      tags:
        - Users
      summary: Add user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Successfully added user
  /users/{id}:
    get:
      operationId: src.endpoints.users.read_one
      tags:
        - Users
      summary: Get specified user
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully read user
    put:
      operationId: src.endpoints.users.update
      tags:
        - Users
      summary: Edit user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User' # BUT NOT PASSWORD_HASH
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully edited user
        403:
          description: Request denied due to lack of permissions
    delete:
      operationId: src.endpoints.users.delete
      tags:
        - Users
      summary: Delete specified user
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully deleted user

  /users/{id}/password:
    put:
      operationId: src.endpoints.users.update_password
      tags:
        - Users
      summary: Change password of specified user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully updated password
        403:
          description: Request denied due to lack of permissions
        404:
          description: Specified user not found

  /users/{id}/projects:
    get:
      operationId: src.endpoints.users.read_projects
      tags:
        - Users
      summary: Get projects of specified user
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully read user projects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        404:
          description: Specified user not found
    post:
      operationId: src.endpoints.users.add_project
      tags:
        - Projects, Users
      summary: Assign a new project to a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        200:
          description: Successfully assigned project to the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
        404:
          description: Specified user or project not found


# ========================================AUTH/LOGOUT==================================================
  /auth:
    post:
      operationId: src.endpoints.auth.login
      tags:
        - Authorization
      summary: User requests token
#      security: [
#        {}
#      ]
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: JWT token
          content:
            'application/json':
              schema:
                type: string
        401:
          description: Unauthorized
  /logout:
    post:
      operationId: src.endpoints.logout.logout
      tags:
        - Authorization
      summary: User logs out and removes cookies
#      security: [
#        {}
#      ]
      responses:
        200:
          description: Unset cookie token
          content:
            'application/json':
              schema:
                type: string


#=========================================================================================================
components:
  parameters:
    id:
      in: path
      name: id
      required: true
      schema:
        type: string
      description: The id number of an object
    path:
      in: query
      name: path
      required: true
      schema:
        type: string
      description: The path to be used

  schemas:
    Project:
      type: object
      properties:
        projectid:
          type: integer
        project_name:
          type: string
        is_archived:
          type: boolean
        create:
          type: string
        last_updated:
          type: string
    User:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        roleid:
          type: integer
        screening_status:
          type: integer
        password_hash:
          type: string
    Announcement:
      type: object
      properties:
        content:
          type: string
        title:
          type: string
    Files:
      type: object
      required:
        - files
      properties:
        files:
          type: array



#  securitySchemes:
#    oAuthSecurity: # <---- arbitrary name
#      type: oauth2
#      description: This API uses OAuth 2 with the password grant flow.
#      x-tokenInfoFunc: src.endpoints.auth.decode_token
#      flows:
#        password: # <---- OAuth flow(authorizationCode, implicit, password or clientCredentials)
#          tokenUrl: /api/auth
#          scopes:
#            {}
#
#
## Step 2 - apply security globally...
#security:
#  - oAuthSecurity: []