DEBUG_MODE = False  # IF TRUE, JWT VERIFICATION AND PERMISSION CHECKING ARE DISABLED!!!
DATABASE_URL = 'mariadb+mariadbconnector://root:admin@127.0.0.1:3306/innovatieplatform'
FILE_STORAGE_ROOT = '../filestorage/root/'

JWT_ISSUER = 'innovatieplatform'
JWT_SECRET = 'kiZn04wb0XEPfpnkTbgmFtHtNElRThM2nWNdD51KaosfRT8HzVLqPB3UMnKPwb1'  # TODO Change This? Moet Secret om de zo veel tijd gerefreshed worden?
JWT_LIFETIME_SECONDS = 3000     # USERS WILL BE REQUIRED TO RE-AUTHENTICATE (LOGIN) AFTER THIS NUMBER OF SECONDS
JWT_ALGORITHM = 'HS256'

ATTEMPTS_BEFORE_COOLDOWN = 6    # COOLDOWN WILL START AFTER THIS NUMBER OF FAILED LOGIN ATTEMPTS
COOLDOWN_TIME_SECONDS = 10      # DURING COOLDOWN, THE API WILL DENY ANY LOGIN ATTEMPTS

CUTOFF_DATE = 0                 # OLDER ANNOUNCEMENTS WILL NOT BE RETURNED BY THE API (0 MEANS ALL ANNOUNCEMENTS WILL BE RETURNED)
MAX_PASSWORD_LENGTH = 60
MIN_PASSWORD_LENGTH = 3
MAX_DIR_NAME = 16               # AMOUNT OF SAFE CHARS ALLOWED IN DIRECTORY NAME
MAX_FILE_NAME = 16              # AMOUNT OF SAFE CHARS ALLOWED IN A FILE NAME
MAX_FILE_SIZE = 100000000       # AMOUNT OF BYTES ALLOWED PER FILE

PASSWORD_CHANGE_SECRET_KEY = "{sPnF[{/Zn-U,&{3KsW\dk*+L%}M'/NW"
DOMAIN_NAME = 'http://localhost:8080'