DEBUG_MODE = False  # IF TRUE, JWT VERIFICATION AND PERMISSION CHECKING ARE DISABLED!!!
DATABASE_URL = 'mariadb+mariadbconnector://root:admin@127.0.0.1:3306/innovatieplatform'

JWT_ISSUER = 'innovatieplatform'
JWT_SECRET = 'kiZn04wb0XEPfpnkTbgmFtHtNElRThM2nWNdD51KaosfRT8HzVLqPB3UMnKPwb1'  # TODO Change This? Moet Secret om de zo veel tijd gerefreshed worden?
JWT_LIFETIME_SECONDS = 600  # USERS WILL BE REQUIRED TO RE-AUTHENTICATE (LOGIN) AFTER THIS NUMBER OF SECONDS
JWT_ALGORITHM = 'HS256'

ATTEMPTS_BEFORE_COOLDOWN = 6  # COOLDOWN WILL START AFTER THIS NUMBER OF FAILED LOGIN ATTEMPTS
COOLDOWN_TIME_SECONDS = 600  # DURING COOLDOWN, THE API WILL DENY ANY LOGIN ATTEMPTS

CUTOFF_DATE = 0  # OLDER ANNOUNCEMENTS WILL NOT BE RETURNED BY THE API (0 MEANS ALL ANNOUNCEMENTS WILL BE RETURNED)
MAX_PASSWORD_LENGTH = 60
